"""
Pipeline configuration for column definitions.

Defines the exact columns expected from OLTP source tables and OLAP target tables.
This serves as the single source of truth for the ETL pipeline schema.
"""

# OLTP Source Columns (from voyla.world OLTP database)
OLTP_COLUMNS = {
    "users": [
        "id",
        "email",
        "display_name",
        "first_name",
        "last_name",
        "avatar_url",
        "gender",
        "provider",
        "created_at",
        "updated_at",
        "found_us_source",
    ],
    "contents": [
        "id",
        "url",
        "html",
        "title",
        "description",
        "site_name",
        "icon_url",
        "preview_image_url",
        "status",
        "created_at",
        "updated_at",
    ],
    "places": [
        "id",
        "google_maps_id",
        "latitude",
        "longitude",
        "english_display_name",
        "zhtw_display_name",
        "english_address",
        "zhtw_address",
        "phone_number",
        "rating",
        "photo_urls",
        "google_map_url",
        "website_url",
        "created_at",
        "updated_at",
        "primary_type",
        "opening_hours",
        "country_code",
        "english_administrative_area",
        "zhtw_administrative_area",
        "english_locality",
        "zhtw_locality",
        "report",
    ],
    "property_mapping": [
        "id",
        "slug",
        "zhtw_display_name",
        "english_display_name",
        "category_type",
        "zhtw_description",
        "source",
        "source_url",
        "is_active",
        "created_at",
        "updated_at",
        "emoji",
        "english_description",
        "cover_img_url",
    ],
    "user_contents": [
        "user_id",
        "content_id",
        "status",
        "is_deleted",
        "created_at",
        "updated_at",
    ],
}

# OLAP Target Columns (from OLAP_schema.sql)
OLAP_COLUMNS = {
    "users": [
        "user_id",
        "email",
        "display_name",
        "avatar_url",
        "found_us_source",
        "created_at",
        "updated_at",
    ],
    "content": [
        "content_id",
        "platform",
        "platform_id",
        "url",
        "thumbnail_url",
        "description",
        "created_at",
        "updated_at",
    ],
    "places": [
        "place_id",
        "google_maps_id",
        "english_display_name",
        "zhtw_display_name",
        "english_address",
        "zhtw_address",
        "phone_number",
        "rating",
        "latitude",
        "longitude",
        "country_code",
        "english_administrative_area",
        "zhtw_administrative_area",
        "english_locality",
        "zhtw_locality",
        "primary_type",
        "created_at",
        "updated_at",
    ],
    "property": [
        "property_id",
        "english_name",
        "zhtw_name",
        "emoji",
        "category_type",
        "created_at",
        "updated_at",
    ],
    "interactions": [
        "user_id",
        "content_id",
        "place_id",
        "property_id",
        "created_at",
        "updated_at",
    ],
}
